export type IllnessTypeRu =
  | "Грипп"
  | "ОРВИ"
  | "Пневмония"
  | "Астма"
  | "Бронхит"
  | "Туберкулёз"
  | "Сахарный диабет"
  | "Гипертония"
  | "Гипотония"
  | "Атеросклероз"
  | "Инфаркт миокарда"
  | "Инсульт"
  | "Аритмия"
  | "Стенокардия"
  | "Гастрит"
  | "Язва желудка"
  | "Панкреатит"
  | "Гепатит A"
  | "Гепатит B"
  | "Гепатит C"
  | "Цирроз печени"
  | "Холецистит"
  | "Пиелонефрит"
  | "Мочекаменная болезнь"
  | "Цистит"
  | "Остеохондроз"
  | "Артрит"
  | "Артроз"
  | "Остеопороз"
  | "Мигрень"
  | "Эпилепсия"
  | "Болезнь Паркинсона"
  | "Альцгеймер"
  | "Шизофрения"
  | "Депрессия"
  | "Тревожное расстройство"
  | "Псориаз"
  | "Экзема"
  | "Акне"
  | "Дерматит"
  | "Глаукома"
  | "Катаракта"
  | "Конъюнктивит"
  | "Отит"
  | "Синусит"
  | "Тонзиллит"
  | "Ангина"
  | "Корь"
  | "Краснуха"
  | "Ветряная оспа"
  | "Бронхиальная астма"
  | "Гепатит";

export type IllnessTypeEn =
  | "flu"
  | "cold"
  | "pneumonia"
  | "asthma"
  | "bronchitis"
  | "tuberculosis"
  | "diabetes"
  | "hypertension"
  | "hypotension"
  | "atherosclerosis"
  | "myocardial_infarction"
  | "stroke"
  | "arrhythmia"
  | "angina"
  | "gastritis"
  | "stomach_ulcer"
  | "pancreatitis"
  | "hepatitis_a"
  | "hepatitis_b"
  | "hepatitis_c"
  | "cirrhosis"
  | "cholecystitis"
  | "pyelonephritis"
  | "kidney_stones"
  | "cystitis"
  | "osteochondrosis"
  | "arthritis"
  | "arthrosis"
  | "osteoporosis"
  | "migraine"
  | "epilepsy"
  | "parkinson"
  | "alzheimer"
  | "schizophrenia"
  | "depression"
  | "anxiety_disorder"
  | "psoriasis"
  | "eczema"
  | "acne"
  | "dermatitis"
  | "glaucoma"
  | "cataract"
  | "conjunctivitis"
  | "otitis"
  | "sinusitis"
  | "tonsillitis"
  | "sore_throat"
  | "measles"
  | "rubella"
  | "chickenpox";

export type IllnessType = IllnessTypeRu | IllnessTypeEn;
