export type OrganTypesRu =
  | "Головной мозг"
  | "Гипофиз"
  | "Щитовидная железа"
  | "Сердце"
  | "Аорта"
  | "Полая вена"
  | "Легкое левое"
  | "Легкое правое"
  | "Бронхи"
  | "Трахея"
  | "Пищевод"
  | "Желудок"
  | "Тонкая кишка"
  | "Толстая кишка"
  | "Печень"
  | "Желчный пузырь"
  | "Поджелудочная железа"
  | "Селезёнка"
  | "Почки"
  | "Надпочечники"
  | "Мочевой пузырь"
  | "Мочеточник"
  | "Мочеиспускательный канал"
  | "Матка"
  | "Яичники"
  | "Простата"
  | "Семенные пузырьки"
  | "Молочные железы"
  | "Лимфатические узлы шеи"
  | "Лимфатические узлы подмышек"
  | "Лимфатические узлы паха"
  | "Подключичная артерия"
  | "Плечевая артерия"
  | "Лучевая артерия"
  | "Подвздошная артерия"
  | "Бедренная артерия"
  | "Сонная артерия"
  | "Воротная вена"
  | "Верхняя полая вена"
  | "Нижняя полая вена"
  | "Спинной мозг"
  | "Крестец"
  | "Копчик"
  | "Мозжечок"
  | "Средний мозг"
  | "Гортань"
  | "Глотка"
  | "Кожа"
  | "Сетчатка"
  | "Хрусталик"
  | "Ухо внутреннее"
  | "Ухо среднее"
  | "Ухо наружное"
  | "Язык"
  | "Нёбо"
  | "Диафрагма"
  | "Синовиальная оболочка"
  | "Лимфатическая система"
  | "Эндокринная система"
  | "Кровеносная система"
  | "Дыхательная система"
  | "Пищеварительная система"
  | "Мочеполовая система"
  | "Центральная нервная система"
  | "Периферическая нервная система"
  | "Скелетная система"
  | "Мышечная система";

export type OrganTypesEn =
  | "Brain"
  | "Pituitary gland"
  | "Thyroid gland"
  | "Heart"
  | "Aorta"
  | "Vena cava"
  | "Left lung"
  | "Right lung"
  | "Bronchi"
  | "Trachea"
  | "Esophagus"
  | "Stomach"
  | "Small intestine"
  | "Large intestine"
  | "Liver"
  | "Gallbladder"
  | "Pancreas"
  | "Spleen"
  | "Kidneys"
  | "Adrenal glands"
  | "Urinary bladder"
  | "Ureter"
  | "Urethra"
  | "Uterus"
  | "Ovaries"
  | "Prostate"
  | "Seminal vesicles"
  | "Mammary glands"
  | "Cervical lymph nodes"
  | "Axillary lymph nodes"
  | "Inguinal lymph nodes"
  | "Subclavian artery"
  | "Brachial artery"
  | "Radial artery"
  | "Iliac artery"
  | "Femoral artery"
  | "Carotid artery"
  | "Portal vein"
  | "Superior vena cava"
  | "Inferior vena cava"
  | "Spinal cord"
  | "Sacrum"
  | "Coccyx"
  | "Cerebellum"
  | "Midbrain"
  | "Larynx"
  | "Pharynx"
  | "Skin"
  | "Retina"
  | "Lens"
  | "Inner ear"
  | "Middle ear"
  | "Outer ear"
  | "Tongue"
  | "Palate"
  | "Diaphragm"
  | "Synovial membrane"
  | "Lymphatic system"
  | "Endocrine system"
  | "Circulatory system"
  | "Respiratory system"
  | "Digestive system"
  | "Genitourinary system"
  | "Central nervous system"
  | "Peripheral nervous system"
  | "Skeletal system"
  | "Muscular system";

export type OrganTypes = OrganTypesRu & OrganTypesEn;
